# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addtoCart = QtWidgets.QPushButton(self.centralwidget)
        self.addtoCart.setGeometry(QtCore.QRect(680, 240, 111, 51))
        self.addtoCart.setStyleSheet("QPushButton {\n"
"    background-color: #444;         /* Default color (dark gray) */\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: cyan;         /* Cyan on hover */\n"
"    color: black;                   /* Optional: change text color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00aaaa;      /* Slightly darker cyan when clicked */\n"
"}")
        self.addtoCart.setObjectName("addtoCart")
        self.productList = QtWidgets.QListWidget(self.centralwidget)
        self.productList.setGeometry(QtCore.QRect(0, 0, 261, 551))
        self.productList.setObjectName("productList")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 0, 411, 561))
        self.groupBox.setObjectName("groupBox")
        self.productName = QtWidgets.QLabel(self.groupBox)
        self.productName.setGeometry(QtCore.QRect(130, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.productName.setFont(font)
        self.productName.setObjectName("productName")
        self.productDescription = QtWidgets.QLabel(self.groupBox)
        self.productDescription.setGeometry(QtCore.QRect(20, 110, 371, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productDescription.sizePolicy().hasHeightForWidth())
        self.productDescription.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.productDescription.setFont(font)
        self.productDescription.setStyleSheet("border: 1px solid #999;\n"
"border-radius: 4px;\n"
"padding: 4px;\n"
"background-color: #fefefe;")
        self.productDescription.setWordWrap(False)
        self.productDescription.setObjectName("productDescription")
        self.productPrice = QtWidgets.QLabel(self.groupBox)
        self.productPrice.setGeometry(QtCore.QRect(150, 250, 81, 21))
        self.productPrice.setStyleSheet("border: 1px solid #999;\n"
"border-radius: 4px;\n"
"padding: 4px;\n"
"background-color: #fefefe;")
        self.productPrice.setObjectName("productPrice")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addtoCart.setText(_translate("MainWindow", "Add To Cart"))
        self.groupBox.setTitle(_translate("MainWindow", "Product Data"))
        self.productName.setText(_translate("MainWindow", "TextLabel"))
        self.productDescription.setText(_translate("MainWindow", "TextLabel"))
        self.productPrice.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
