# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shopping_cart.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cartList = QtWidgets.QListWidget(self.centralwidget)
        self.cartList.setObjectName("cartList")
        self.verticalLayout.addWidget(self.cartList)
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setStyleSheet("QPushButton {\n"
"    background-color: #444;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: cyan;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #00aaaa;\n"
"}")
        self.returnButton.setObjectName("returnButton")
        self.verticalLayout.addWidget(self.returnButton)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setStyleSheet("QPushButton {\n"
"    background-color: #444;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: cyan;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #00aaaa;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.verticalLayout.addWidget(self.backButton)
        self.purchaseButton = QtWidgets.QPushButton(self.centralwidget)
        self.purchaseButton.setStyleSheet("QPushButton {\n"
"    background-color: #444;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: cyan;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #00aaaa;\n"
"}")
        self.purchaseButton.setObjectName("purchaseButton")
        self.verticalLayout.addWidget(self.purchaseButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.returnButton.setText(_translate("MainWindow", "Return Product"))
        self.backButton.setText(_translate("MainWindow", "Go Back"))
        self.purchaseButton.setText(_translate("MainWindow", "Purchase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
